// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  File = 2,
  Colon = 3,
  Period = 4,
  FVar = 5,
  Identifier = 6,
  Pragma = 7,
  Arrow = 8,
  Type = 9
